# Generated by Django 3.2.8 on 2021-10-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAverage',
        ),
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
