# Generated by Django 3.2.8 on 2021-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
